#pragma once

#include "Ability.h"
#include "ConstructBarracks.h"
#include "ConstructDragonLair.h"
#include "ConstructGemsMine.h"
#include "ConstructIronMine.h"
#include "ConstructFarm.h"
#include "ConstructLumberjacksHut.h"
#include "ConstructStable.h"
#include "ConstructShipyard.h"
#include "HireDragon.h"
#include "Pillage.h"
#include "TrainArcher.h"
#include "TrainHorseman.h"
#include "TrainSwordsman.h"